name: Docker Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ghcr.io/openfaas/nats-connector:latest-dev
