name: CI

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # DOCKER_NS: "openfaas"
      DOCKER_NS: "codecutteruk"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: make build
        run: make build
