name: publish

on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Get repo owner in lowercase
        id: get_repo_owner
        run: echo ::set-output name=REPOSITORY_OWNER_LOWER::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        # run: echo ::set-output name=REPOSITORY_OWNER_LOWER::${GITHUB_REPOSITORY_OWNER,,}

      - name: get_repo_owner_print
        id: get_repo_owner_print
        run: echo ${{ steps.get_repo_owner.outputs.REPOSITORY_OWNER_LOWER }}

      - name: get_repo_owner_event
        id: get_repo_owner_event
        run: echo ::set-output name=REPOSITORY_OWNER_LOWER::$(echo ${{ github.event.repository.owner.login }} | tr '[:upper:]' '[:lower:]')

      - name: get_repo_owner_event_print
        id: get_repo_owner_event_print
        run: echo ${{ steps.get_repo_owner.outputs.REPOSITORY_OWNER_LOWER }}

      - name: repo_owner_from_env
        id: test1
        run: echo ${GITHUB_REPOSITORY_OWNER}

 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io

      - name: Build image and push to container registies
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          outputs: "type=image,push=false"
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            FULL_REPO_NAME=${{github.repository}}
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.REPOSITORY_OWNER_LOWER }}/nats-connector:${{ github.sha }}
            ghcr.io/${{ steps.get_repo_owner.outputs.REPOSITORY_OWNER_LOWER }}/nats-connector:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ steps.get_repo_owner.outputs.REPOSITORY_OWNER_LOWER }}/nats-connector:latest
